// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://juxqlzbngxwqqkeupimc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1eHFsemJuZ3h3cXFrZXVwaW1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MDIyNTUsImV4cCI6MjA3MTk3ODI1NX0.pE7xUMrRn5apHd4XgsJMmlJlEIgXxsba_HvZk_Vv6hk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});